default_language_version:
    python: python3.8

default_stages: [commit, push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          # Python checks
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-ast
          - id: check-builtin-literals
          - id: check-docstring-first
          - id: debug-statements
          - id: fix-encoding-pragma

          # Git checks
          - id: check-merge-conflict
          - id: forbid-new-submodules
          #- id: no-commit-to-branch
          #args: [--branch, main]

          # check certain types of files
          - id: check-yaml
          - id: check-xml
          - id: check-json

          # Others
          - id: end-of-file-fixer
            #exclude_types: ['html', 'css', 'javascript', 'svg',]
          - id: trailing-whitespace
            #args: [--markdown-linebreak-ext=md]
            #exclude_types: ['javascript']
          - id: detect-private-key
          - id: check-symlinks
          - id: check-case-conflict
          - id: check-added-large-files
            #args: ['--maxkb=2000']

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            args: [--line-length=79]
            verbose: True
            #exclude: migrations

    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            args: ["--ignore=E501,E301,E302,F401"]
            verbose: True

    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
          - id: isort
            verbose: True